name: Build_and_test_compose

on:
  pull_request:
    branches:
    - main

env:
  NGINX_HOST: http://localhost:4000
  MYSQL_USER: ${{ secrets.MYSQL_USER }}
  MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD}}
  MYSQL_HOST: ${{ secrets.MYSQL_HOST}}
  MYSQL_PORT: ${{ secrets.MYSQL_PORT}}
  MYSQL_DB: ${{ secrets.MYSQL_DB}}
  REDIS_URL: ${{ secrets.REDIS_URL}}
  REDIS_QUEUES: ${{ secrets.REDIS_QUEUES}}
  CACHE_TYPE: ${{ secrets.CACHE_TYPE}}
  CACHE_TIMEOUT: ${{ secrets.CACHE_TIMEOUT}}

jobs:
  docker:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
    - name: Repository Checkout
      uses: actions/checkout@v2

    - name: Create .env
      uses: CallePuzzle/envvar-to-dotenv-action@v1.0.0
      with:
        variableNamesByFilter: ^.*

    - name: Build containers
      uses: BearDimonR/highload_architecture/.github/actions/build_compose_action@v1
      
    - name: Start containers
      run: docker-compose -f "docker-compose.yml" up
    
    - name: Test API
      run: BearDimonR/highload_architecture/.github/actions/test_compose_action@v1

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down
