name: Build_and_test_compose

on:
  pull_request:
    branches:
    - main
jobs:
  docker:
    environment: compose
    env:
      NGINX_HOST: http://localhost:4000
      MYSQL_USER: librarian
      MYSQL_PASSWORD: pass
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DB: library
      REDIS_URL: redis://redis:6379/0
      REDIS_QUEUES: default
      CACHE_TYPE: redis
      CACHE_DEFAULT_TIMEOUT: 500
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
    - name: Repository Checkout
      uses: actions/checkout@v2

    - name: Create .env
      uses: CallePuzzle/envvar-to-dotenv-action@v1.0.0
      with:
        variableNamesByFilter: ^.*

    - name: Build containers
      uses: BearDimonR/highload_architecture/.github/actions/build_compose_action@v4
      
    - name: Start containers
      run: docker-compose -f "docker-compose.yml" up -d
    
    - name: Test API
      uses: BearDimonR/highload_architecture/.github/actions/test_compose_action@v4


    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down
