name: Build_and_test_compose

on:
  pull_request:
    branches:
    - main

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Repository Checkout
      uses: actions/checkout@v1

    - name: Start containers
      run: docker-compose -f "docker-compose.yml" up -d --build

    - name: Install node v14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x

    - name: Install tests dependencies
      run: npm i
      working-directory: ./tests

    - name: Run tests
      run: HOST=${NGINX_HOST} npm run test
      working-directory: ./tests
      env:
        NGINX_HOST: nginx

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down