name: Deploy_compose

on:
  pull_request:
    branches:
    - main
jobs:
  simple-deploy:
      name: Deploy docker-compose to AWS ECS
      environment: compose
      runs-on: ubuntu-latest
      env:
        AWS_REGION: ap-southeast-1
        APP_NAME: "highload"
        AWS_ECR_ADDRESS: ${{ secrets.AWS_ECR_ADDRESS }}
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        BUILD_ID: ${{ github.run_number }}
      steps:
        - name: Configure AWS credentials
          run: |
            aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
            aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
            aws configure set region "$AWS_REGION"
            aws configure set output json
        - name: ls
          run: ls
        - name: Push to ECR
          run: |
            chmod +x /deploy.sh
            sh ./deploy.sh build-to-ecr $AWS_REGION $APP_NAME $AWS_ECR_ADDRESS $AWS_ACCOUNT_ID $BUILD_ID
        - name: Deploy to Fargate
          run: |
            sh ./deploy.sh deploy